### ISSUE TITLE
What?!

### ISSUE THREAD

**Issue by andybrwr** [ScratchAT/CustomForum#1]
THIS IS POSSIBLE?!
nooooooooooo u liar

**Comment by haylinmoore** [comment]
Oh trust it will work >:) me an leafy have some good ideas >:)

**Comment by andybrwr** [comment]
you hacker
btw will this be whitelisted? you could use this instead of gitter lol

**Comment by haylinmoore** [comment]
No sir! You will just the US

**Comment by andybrwr** [comment]
wait what? how do I just the us :3

**Comment by haylinmoore** [comment]
US=userscript

**Comment by andybrwr** [comment]
oh xD sorry i know nothing
updating comments like crazy and just realized that github has async issue updating

**Comment by andybrwr** [comment]
cheater :P

**Comment by haylinmoore** [comment]
How?

**Comment by andybrwr** [comment]
nvm :P

**Comment by haylinmoore** [comment]
May I close this now?

**Comment by andybrwr** [comment]
ye

**Comment by andybrwr** [comment]
wth

**Comment by haylinmoore** [comment]
;P

**Comment by andybrwr** [comment]
y u spam my homepage lol

**Comment by haylinmoore** [comment]
I was bored

**Comment by andybrwr** [comment]
revenge
